version: '2'
services:
  server:
    build: .
    depends_on: 
      - mongodb
    ports:
      - "3001:3001"
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
  mongodb:
    image: mongo
    ports: 
      - "27017:27017"
    volumes:
      - mongodata:/data/db
volumes:
  mongodata: