swagger: "2.0"
info:
  version: "1.0.0"
  title: "Servicio de información de clientes"
tags: 
- name: "User"
  description: "Información del usuario."
- name: "Establishment"
  description: "Información del estableciemiento."
paths:
  /clients/{id}:
    get:
      tags:
      - "User"
      summary: "Obtiene la información del cliente."
      parameters:
      - in: "path"
        name: "id"
        description: "Id del cliente."
        required: true
        type: "integer"
      responses:
        200:
          description: "La solicitud fue exitosa."
          schema:
            $ref: "#/definitions/User"
        404:
          description: "El usuario solicitado no existe."
    put:
      tags:
      - "User"
      summary: "Modifica la información del cliente"
      parameters:
      - in: "path"
        name: "id"
        description: "Id del cliente."
        required: true
        type: "integer"
      - in: "body"
        name: "body"
        required: true
        description: "Objeto que contiene sólo los cambios en la información."
        schema:
            $ref: "#/definitions/User"
      responses:
        204:
          description: "La solicitud fue exitosa."
        400:
          description: "La solicitud no tiene los parámetros requeridos."
  /clients:
    post:
      tags:
      - "User"
      summary: "Añade un nuevo cliente."
      parameters:
      - in: "body"
        name: "body"
        description: "Objeto con la información del usuario."
        required: true
        schema:
          $ref: "#/definitions/User"
      consumes:
      - "application/json"
      produces:
      - ""
      responses:
        201:
          description: "El nuevo cliente fue creado exitosamente."
        400:
          description: "La solicitud no tiene los parámetros requeridos."
  /establishments:
    get:
      tags:
      - "Establishment"
      summary: "Obtiene los establecimientos cercanos que cumplan con ciertos filtros"
      parameters:
      - in: "query"
        name : "coordinateX"
        description : "Coordenada x de ubicación del cliente."
        required : true
        type : "number"
        format : "float"
      - in: "query"
        name : "coordinateY"
        description : "Coordenada y de ubicación del cliente."
        required : true
        type : "number"
        format : "float"
      - in: "query"
        name : "minimumScore"
        description : "Puntaje mínimo aceptado para un establecimiento."
        type : "integer"
      - in: "query"
        name : "maximumDeliveryTime"
        description : "Tiempo máximo de entrega aceptado para un establecimiento (en minutos)."
        type : "integer"
      - in: "query"
        name : "maximumDeliveryCost"
        description : "Costo máximo de entrega aceptado para un establecimiento."
        type : "integer"
      responses:
        200:
          description: "La solicitud fue exitosa"
          schema:
            $ref: '#/definitions/Establishment'
    post:
      tags:
      - "Establishment"
      summary: "Añade un nuevo establecimiento."
      produces:
      - ""
      parameters:
      - in: "body"
        name: "body"
        description: "Objeto con la información del establecimiento."
        required: true
        schema:
          $ref: '#/definitions/InputEstablishment'
      responses:
        201:
            description: "El nuevo establecimiento fue creado exitosamente."
        400:
          description: "La solicitud no tiene los parámetros requeridos."
  /establishments/{id}:
    get:
      tags:
      - "Establishment"
      summary: "Obtiene un establecimiento identificado por su id."
      parameters:
      - in: "path"
        name : "id"
        description : "Id del establecimiento."
        required : true
        type : "number"
      responses:
        200:
          description: "La solicitud fue exitosa"
          schema:
            $ref: '#/definitions/Establishment'
    put:
      tags:
      - "Establishment"
      summary: "Modifica la información de un establecimiento."
      produces:
      - ""
      parameters:
      - in: "path"
        name : "id"
        description : "Id del establecimiento."
        required : true
        type : "number"
      - in: "body"
        name: "body"
        description: "Objeto con la información del establecimiento."
        required: true
        schema:
          $ref: '#/definitions/InputEstablishment'
      responses:
        201:
            description: "El nuevo establecimiento fue creado exitosamente."
        400:
          description: "La solicitud no tiene los parámetros requeridos."
  /establishments/{id}/messages:
    post:
      tags:
      - "Establishment"
      summary: "Añade un nuevo mensaje (reseña) a un establecimiento."
      produces:
      - ""
      parameters:
      - in: "path"
        name : "id"
        description : "Id del establecimiento."
        required : true
        type : "number"
      - in: "body"
        name: "body"
        description: "Objeto con la información del mensaje."
        required: true
        schema:
          $ref: '#/definitions/Message'
      responses:
        201:
            description: "El nuevo mensaje fue añadido exitosamente."
        400:
          description: "La solicitud no tiene los parámetros requeridos."
definitions:
  User:
    type: "object"
    properties:
      name:
        type: "string"
      lastname:
        type: "string"
      email:
        type: "string"
        format: "email"
  InputEstablishment:
    type: "object"
    properties:
      name:
        type: "string"
      coordinateX:
        type: "number"
        format: "float"
      coordinateY:
        type: "number"
        format: "float"
      address:
        type: "string"
        format: "email"
      deliveryTime:
        type: "integer"
      deliveryCost:
        type: "number"
      paymentMethods:
        type: "array"
        items: 
          type : "string"
      type:
        type: "string"
        enum: ["Restaurant","Market","Drinks","Drugstore","Petstore","Store"]
      categories:
        type: "array"
        items:
          type: "string"
  Establishment:
    type: "object"
    properties:
      name:
        type: "string"
      coordinateX:
        type: "number"
        format: "float"
      coordinateY:
        type: "number"
        format: "float"
      address:
        type: "string"
        format: "email"
      deliveryTime:
        type: "integer"
      deliveryCost:
        type: "number"
      paymentMethods:
        type: "array"
        items: 
          type : "string"
      type:
        type: "string"
        enum: ["Restaurant","Market","Drinks","Drugstore","Petstore","Store"]
      categories:
        type: "array"
        items:
          type: "string"
      score: 
        type: "number"
        format: "float"
      messages:
        type: "array"
        items:
          $ref: '#/definitions/Message'
      nMessages:
        type: "integer"
  Message:
    type: "object"
    properties:
      idPoster:
        type: "string"
        format: "hex"
        minLength: 24
        maxLength: 24
      text:
        type: "string"
      score:
        type: "integer"
        maximum: 5
        minimum: 1